// www/src/components/Terminal.tsx
import { FitAddon } from "@xterm/addon-fit";
import { WebglAddon } from "@xterm/addon-webgl";
import {
  type ITerminalInitOnlyOptions,
  type ITerminalOptions,
  Terminal as XTerm,
} from "@xterm/xterm";
import "@xterm/xterm/css/xterm.css";
import { onCleanup, onMount } from "solid-js";

export function createTerminal(
  init?: ITerminalInitOnlyOptions & ITerminalOptions,
) {
  const term = new XTerm(init);
  const fitAddon = new FitAddon();
  term.loadAddon(fitAddon);

  function Terminal() {
    let self!: HTMLDivElement;

    onMount(() => {
      term.open(self);
      const webglAddon = new WebglAddon();
      term.loadAddon(webglAddon);

      webglAddon.onContextLoss(() => {
        webglAddon.dispose();
      });

      fitAddon.fit();

      const handleResize = () => fitAddon.fit();
      globalThis.addEventListener("resize", handleResize);

      onCleanup(() => {
        term.dispose();
        globalThis.removeEventListener("resize", handleResize);
        self.replaceChildren();
      });
    });

    return <div class="h-full w-full" ref={self} />;
  }
  return [term, Terminal] as const;
}

// www/src/lib/Terminal.svelte
<script lang="ts">
  import {
    type ITerminalOptions,
    type ITerminalInitOnlyOptions,
    Terminal,
  } from "@xterm/xterm";
  import "@xterm/xterm/css/xterm.css";
  import { FitAddon } from "@xterm/addon-fit";
  import { WebglAddon } from "@xterm/addon-webgl";

  interface Props {
    term: Terminal | undefined;
    options?: ITerminalOptions & ITerminalInitOnlyOptions;
  }

  let { term = $bindable(), options }: Props = $props();

  function bindTerm(el: HTMLElement) {
    const instance = new Terminal(options);
    const fitAddon = new FitAddon();
    instance.loadAddon(fitAddon);
    instance.open(el);

    try {
      const webglAddon = new WebglAddon();
      instance.loadAddon(webglAddon);
    } catch (e) {
      console.error("WebGL failed", e);
    }

    fitAddon.fit();
    term = instance;

    const handleResize = () => fitAddon.fit();
    globalThis.addEventListener("resize", handleResize);

    return () => {
      globalThis.removeEventListener("resize", handleResize);
      instance.dispose();
      term = undefined;
    };
  }
</script>

<div class="h-full w-full" {@attach bindTerm}></div>
